name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  saveModel:
    name: Save Model and Upload Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Train the model with the training data and save the best model
        run: python train.py
        
      - name: Store trained model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: models/
  lint:
    name: Lint Code with Pylint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.15
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run Pylint
      run: |
        pylint app.py tests/

  test:
    name: Run Pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.15
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run Pytest
      run: |
        pytest --maxfail=1 --disable-warnings

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and Run Docker Container
      run: |
        docker build -t flask-app .
        docker run -d -p 5000:5000 flask-app
